### ISSUE TITLE
Being able to add enchantment to the table without using chiseled bookshelves

### ISSUE THREAD

**Issue by Kirisoup** [AstralOrdana/Enchantery#6]
_enchantery 0.0.8_

_quilt loader 0.21.0-beta.3_

_minecraft 1.20.1_

Having enchanted books in containers other than chiseled bookshelves (like dispensers, chests) still contribute to the enchantments shown in the table, eventhough they shouldn't.

**Comment by Kirisoup** [comment]
This problem is encountered when other mods are installed. Let me try only your mod and if the problem still exist.

---

Edit: can confirm that this issue is still present with only the following mods:

- Quilted Fabric API `qfapi-7.2.2_qsl-6.1.2_fapi-0.88.1_mc-1.20.1`
- Moonlight `1.20-2.8.25`
- Enchantery `1.20.1-0.0.8`

**Comment by AstralOrdana** [comment]
working as intended. chiseled bookshelves are the containers players are expected to use for this mechanic but it is being left as any container type so as to support other modded containers that can store books such as supplementaries' placeable enchanted books
